import Image from "next/image";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { WorldMediaGrid } from "@/components/sections/world-media-grid";
import aboutStyles from "@/components/sections/about-dayanne.module.css";
import { BrandsEditorial } from "@/components/sections/brands-editorial";
import { CommunityHub } from "@/components/sections/community-hub";
import { TextReveal } from "@/components/ui/text-reveal";
import { MobileMenu } from "@/components/ui/mobile-menu";

export default function Home() {
  return <main><TextReveal />
    <header className="topbar"><a className="brand" href="#inicio">DAYANNE<br/>COSTA<span>.</span></a><nav aria-label="Navegação principal"><a href="#mundo">CONTEÚDO</a><a href="#sobre">SOBRE</a><a href="#marcas">MARCAS</a><a href="#comunidade">COMUNIDADE</a><a href="#contato">MÍDIA KIT</a><a href="#contato">CONTATO</a></nav><div className="header-actions"><div className="social-links" aria-label="Redes sociais"><a href="https://www.instagram.com/dayannecostaig/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" className="fill"/></svg></a><a href="https://www.tiktok.com/@djdaycosta" target="_blank" rel="noreferrer" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 3v11.2a4.2 4.2 0 1 1-3.1-4.05"/><path d="M14 3c.65 2.55 2.1 4 4.7 4.45"/></svg></a><a href="https://open.spotify.com/user/daycsanttos?si=zYzn2JkuQbeKNDfo_DCKSQ&nd=1&dlsi=60ef76ee19f44e46" target="_blank" rel="noreferrer" aria-label="Spotify"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M7.5 10.2c3.8-1.1 6.7-.65 9.2.55M8 13.1c3.1-.8 5.55-.4 7.6.5M8.6 15.7c2.45-.55 4.2-.25 5.7.38"/></svg></a></div><a className="nav-cta" href="#contato">TRABALHE COMIGO <ArrowUpRight size={15}/></a></div><MobileMenu /></header>
    <section id="inicio" className="hero"><Image priority fill sizes="100vw" quality={95} className="cover hero-photo" src="/dayanne-hero.png" alt="Dayanne Costa ao ar livre, em look esportivo preto durante a golden hour"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow light">CREATOR · RUNNER · LIFESTYLE</p><h1>DAYANNE<br/><i>COSTA</i></h1><p className="hero-statement">Mais que conteúdo,<br/>uma vida em movimento.</p><p className="hero-description">Esporte, bem-estar, moda, viagens e experiências que fazem parte da vida real.</p><div className="hero-actions"><a className="pink-button" href="#contato">TRABALHE COMIGO <ArrowUpRight size={17}/></a><a className="hero-secondary" href="#mundo">VER CONTEÚDO <ArrowDownRight size={16}/></a></div></div><div className="hero-stats"><div><strong>168,9K</strong><span>SEGUIDORES</span><small>Instagram + TikTok</small></div><div><strong>8M</strong><span>ALCANCE MENSAL</span></div><div><strong>4,7%</strong><span>ENGAJAMENTO</span></div></div><div className="hero-bottom"><span>SCROLL<br/>PARA EXPLORAR</span><ArrowDownRight size={20}/></div></section>
    <section id="mundo" className="world"><div className="heading"><p className="eyebrow">O UNIVERSO</p><h2>MAIS DO QUE<br/><i>CONTEÚDO.</i></h2><p>Uma presença em movimento entre esporte, estilo e vida real.</p></div><WorldMediaGrid /></section>
    <section id="sobre" className="about"><Image fill sizes="100vw" quality={90} className="cover" src="/dayanne-about.png" alt="Colagem editorial de Dayanne Costa como creator, DJ e apresentadora"/><div className="about-shade"/><div className={`about-copy ${aboutStyles.copy}`}><p className="eyebrow light">SOBRE DAYANNE</p><h2 className={aboutStyles.headline}>MUITO ALÉM<br/>DO <i>CONTEÚDO.</i></h2><p className={aboutStyles.text}>Dayanne é creator, DJ e apresentadora. Entre esporte, moda, lifestyle e eventos, transforma a rotina em conteúdo — dentro e fora das telas.</p><p className={aboutStyles.roles}>CREATOR · DJ · APRESENTADORA</p></div></section>
    <BrandsEditorial />
    <CommunityHub />
    <section className="kit"><p className="eyebrow light">PARCERIAS &amp; PROJETOS</p><h2>VAMOS CRIAR<br/><i>ALGO FORTE.</i></h2><div><p>Apresentação, formatos e oportunidades para marcas que se movem com propósito.</p><a className="dark-button" href="#contato">SOLICITAR MÍDIA KIT <ArrowDownRight size={17}/></a></div></section>
    <footer id="contato"><p className="eyebrow light">CONTATO</p><h2>FALA<br/><i>COMIGO.</i></h2><a className="mail" href="mailto:contato@dayannecosta.com">CONTATO@DAYANNECOSTA.COM <ArrowUpRight/></a><div className="footer-bottom"><a className="brand" href="#inicio">DAYANNE<br/>COSTA<span>.</span></a><p>© 2026 DAYANNE COSTA.</p><p className="footer-credit">DESENVOLVIDO POR <a href="https://lp.marzcreativedesign.com" target="_blank" rel="noopener noreferrer" style={{ textDecoration: "underline", color: "inherit", opacity: 0.9 }}>RAFAEL SETUBAL</a></p></div></footer>
  </main>;
}
